---

- name: Install ImageMagick (Debian)
  apt: pkg=imagemagick
  when: ansible_os_family == "Debian"
  sudo: true

- name: Install ImageMagick (Red Hat)
  yum: pkg={{ item }} state=installed
  when: ansible_os_family == "RedHat"
  sudo: true
  with_items:
    - ImageMagick
    - ImageMagick-devel
